// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnY4rpzng4UB13uia9eePh0ip98zFdJu0',
    appId: '1:725875175343:web:2387905b439cc3c27f895a',
    messagingSenderId: '725875175343',
    projectId: 'pure-album-408119',
    authDomain: 'pure-album-408119.firebaseapp.com',
    storageBucket: 'pure-album-408119.appspot.com',
    measurementId: 'G-Q05R57XKC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRGtuBw3xA0s7rQKvEyKIn_ysdr2K-No',
    appId: '1:725875175343:android:4993865d43544e8d7f895a',
    messagingSenderId: '725875175343',
    projectId: 'pure-album-408119',
    storageBucket: 'pure-album-408119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7ueg_3j7UsL6Qj71JIiCHrKu6s2HNdw',
    appId: '1:725875175343:ios:b0a74d73b8ed59247f895a',
    messagingSenderId: '725875175343',
    projectId: 'pure-album-408119',
    storageBucket: 'pure-album-408119.appspot.com',
    iosBundleId: 'com.example.frontendNdfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF7ueg_3j7UsL6Qj71JIiCHrKu6s2HNdw',
    appId: '1:725875175343:ios:b5d26cae651d6fc47f895a',
    messagingSenderId: '725875175343',
    projectId: 'pure-album-408119',
    storageBucket: 'pure-album-408119.appspot.com',
    iosBundleId: 'com.example.frontendNdfy.RunnerTests',
  );
}
